### ISSUE TITLE
(Bug when using Reggie Milestone 2 alpha3)  There is a bug related to sprite 306 (Rotating Spotlight) when opening World 5 Ghost House.

### ISSUE THREAD

**Issue by interstatepr53** [RoadrunnerWMC/Reggie-Next#14]
The level won't loaded when is was opened in the first time (0%) and when I restarted the program, I got this error:

**File "C:\Reggie-Next\sprites.py", line 5100, in updateSize 
AttributeError: 'SpriteImage_RotSpotlight' object has no attribute 'spritedata'**

Also the editor refuse to place this sprite on any level.

See the Screenshots bellow.
Trying to open World 5-Ghost House
![screenshot 444](https://user-images.githubusercontent.com/13475579/27620313-c47f555e-5b96-11e7-97df-d51b7df4c30d.png)

The errors after restarting reggie.
![screenshot 443](https://user-images.githubusercontent.com/13475579/27620117-4c2a1e1e-5b95-11e7-840b-f0dc6aac43d0.png)

**Comment by RoadrunnerWMC** [comment]
This is the same kind of issue as #13 from last month, and the workaround is the same.
