### ISSUE TITLE
Newer Mode Seemingly Not Working

### ISSUE THREAD

**Issue by Chickensaver** [RoadrunnerWMC/Reggie-Next#15]
Hello!  While I was using Reggie-Next, I realized that opening my previously made levels while still on the normal nsmbw mode would be problematic seeing as they had newer sprites in them.  When looking at the game-modes though, I found that the only game-mode there was was nsmbw.  Here is what I found:

![capture](https://user-images.githubusercontent.com/27451052/28500040-236193ae-6f90-11e7-8a7b-ca1149fffa68.PNG)

Does this beta version not yet support NewerSMBW or am I just doing something terribly wrong?
P.S. I am perfectly fine with using the older versions of Reggie-Next that don't have this "problem" so you do not need to pay any attention to this issue if you have better things to do with your time.
😃

**Comment by RoadrunnerWMC** [comment]
(Sorry for the delayed reply; I was away for a while...)

It's a separate download:
https://www.dropbox.com/s/pxbluquzn4l1s1t/NewerGamePatchBeta.zip?dl=1

**Comment by Chickensaver** [comment]
No need to apologize.  You're about the only person that I know of that has large knowledge about nsmbw hacking so it's a wonder that I even have a place to ask questions.  Anyway, thanks for letting me know about the separate download.

**Comment by ehx-v1** [comment]
I think I should mention it's somewhat of a problem that this is, as it seems, not documented anywhere. I read through the entire Readme, and there's not even a mention of the Newer Mode download.

**Comment by Bahlph** [comment]
This is **very** unfinished, but here is a documentation a bunch of people have been creating for nsmbw.  I would recommend joining the discord, as more things happen there and progress is not fast on the wiki.

https://horizon.miraheze.org/wiki/Main_Page

**Comment by shinoff2183** [comment]
I download the newer patch beta file. Where do I put that file

**Comment by Bahlph** [comment]
https://horizon.miraheze.org/wiki/Main_Page
Feel free to go to that wiki page, or if you want direct help, you can ask me or anyone else in the NSMBW modding community at https://discord.gg/XnQJnwa.

**Comment by shinoff2183** [comment]
> https://horizon.miraheze.org/wiki/Main_Page
> Feel free to go to that wiki page, or if you want direct help, you can ask me or anyone else in the NSMBW modding community at https://discord.gg/XnQJnwa.

I've never been on discord before but I'm trying it out. I accepted the invite and now it just seems stuck. I'm trying to click on one of the rooms. Expletive "downloads" or "modding" but it doesn't do anything. I'm probably missing something real stupid that I haven't done.
