### ISSUE TITLE
Reggie Next rejects valid NSMBW Stage folder

### ISSUE THREAD

**Issue by domcarminefilix** [RoadrunnerWMC/Reggie-Next#20]
Hello, I don't know if I will ever get a reply but it I do I would like it, so I downloaded Reggie Next and as I went to select my stage folder, it didn't work saying it didn't have the required files. I have made 0 modifications to it and I ripped it straight from the game itself. It seems to work fine on normal Reggie though, any ideas?

**Comment by RoadrunnerWMC** [comment]
Make sure that mode.txt contains "W" as the first character and not "2". This puts the editor into New Super Mario Bros. Wii mode instead of New Super Mario Bros. 2 mode.
