### ISSUE TITLE
The modified levels doesn't works with riivolution.

### ISSUE THREAD

**Issue by arthuro555** [RoadrunnerWMC/Reggie-Next#23]
When I try to use the level files on riifs with riivolution, the levels are exactly like normal. But with the normal reggie! it works just fine.

**Comment by RoadrunnerWMC** [comment]
Hm, I've never heard of this before. Have you tried loading the levels via some other method? I've never used RiiFS, so I can't really help with that loading method in particular.

**Comment by arthuro555** [comment]
I mean that they are loaded and patched into memory but the levels are the Originals ones. When I open the levels edited with this editor un another Reggie! Fork or the original, I see the original level, but on this editor only I Can see thé changes.

EDIT: Forgot to Say that I'm using the precompiled binaries as the source doesn't work (on latest commit python 3.4 says indentation error).

**Comment by RoadrunnerWMC** [comment]
It sounds like you might have made two separate Stage folders and accidentally configured your various copies of Reggie to use different ones; that would explain why changes you make with some of them can't be seen in others or in-game. Could you check if this is the case?
