### ISSUE TITLE
Sprites disappear when out of screen

### ISSUE THREAD

**Issue by yes919** [RoadrunnerWMC/Reggie-Next#25]
I'm new to Reggie, so I have no idea what I'm doing wrong.

Gif example:

![](https://user-images.githubusercontent.com/58666825/70394782-70023c80-19f8-11ea-8b6c-35c8b0090c7c.gif)

**Comment by yes919** [comment]
How it's supposed to look like
![Capture](https://user-images.githubusercontent.com/58666825/70458237-fe86c480-1ab1-11ea-9ff7-39dd2d819edc.PNG)

**Comment by RoadrunnerWMC** [comment]
Hi! I've never seen this particular issue before, but I'll try to help anyway.

My own guess is that the "bias" checkbox in the zone settings is set incorrectly. Nobody's really sure exactly what it does, but sometimes checking or unchecking it can fix weird issues like this.

I also asked about this in a Discord server I'm in, and got this response:
> this specific issue i've seen before
> but i forgot what the solution was :(
> i think it was something like conflicting event trigger ids
> but i'm not sure

Anyway... I know that's not very much, but I hope that helps a little. Good luck!

**Comment by yes919** [comment]
Thank you for replying, and you are correct. I ticked the "bias" checkbox and the problem was solved.
