### ISSUE TITLE
Another weird issue - thwomps appear only after the camera has scrolled past their position.

### ISSUE THREAD

**Issue by yes919** [RoadrunnerWMC/Reggie-Next#26]
GIF example:

![ezgif-4-b4fa68552e29](https://user-images.githubusercontent.com/58666825/70834036-93aef380-1df9-11ea-9cc6-ef568c8fa941.gif)

**Comment by RoadrunnerWMC** [comment]
> **\<Skawo\>** that issue is caused by the thwomp being too high in the zone
> **\<Bent\>** what would cause that though?
> **\<Skawo\>** not sure
> **\<Skawo\>** but I did run into this once and that was the problem

**Comment by yes919** [comment]
Thanks, it works!
