### ISSUE TITLE
Nothing's happining

### ISSUE THREAD

**Issue by Shyguyfan101** [RoadrunnerWMC/Reggie-Next#27]
Python won't let me open reggie.py for some reason. And I really want to open Reggie.py

**Comment by Meorge** [comment]
Can you be more specific? When you try to run `reggie.py`, does anything get printed to the command line/Terminal? What operating system and version are you on?

**Comment by Shyguyfan101** [comment]
I'm on Windows 10

**Comment by Meorge** [comment]
How are you attempting to run Reggie Next (specific steps)?

**Comment by Shyguyfan101** [comment]
All of the steps are confusing to me.

**Comment by Meorge** [comment]
If we don't know what you're trying to do in order to run Reggie Next, we won't be able to help you.
Are you on the NSMBW Hacking Depot, by chance? If so, I may be able to help you there more quickly.

**Comment by Shyguyfan101** [comment]
What am I supposed to do in the installer for reggie.py?

**Comment by Meorge** [comment]
I don't think there is an installer for `reggie.py`. If you want to run it from source (using the `.py` file itself), you'll have to run `python reggie.py` or a similar command from the command line.

**Comment by Shyguyfan101** [comment]
![image](https://user-images.githubusercontent.com/73045476/99920216-e2862e00-2cd6-11eb-912a-85e0ac2993e6.png)

**Comment by Meorge** [comment]
It looks like you're trying to run the `python reggie.py` command from within the Python command line. How are you getting to the window with the `>>>`?

**Comment by Shyguyfan101** [comment]
Python had the command `>>>` when I booted Python.

**Comment by Meorge** [comment]
How did you boot Python?

**Comment by Shyguyfan101** [comment]
I used the search bar.

**Comment by Meorge** [comment]
Okay. Can you open the Command Prompt and type the following?
```
cd [path to folder with reggie.py]
```

replacing `[path to folder with reggie.py]` with the corresponding folder path, of course.

**Comment by Shyguyfan101** [comment]
I did that. So what's next?

**Comment by Meorge** [comment]
Try typing
```
python reggie.py
```
and press Enter/Return

**Comment by Shyguyfan101** [comment]
![image](https://user-images.githubusercontent.com/73045476/99924710-2cc7d900-2cf0-11eb-8134-00a1076b285d.png)

**Comment by Meorge** [comment]
Did you install [all of the dependencies listed here](https://github.com/RoadrunnerWMC/Reggie-Next#how-to-run-reggie-from-source)? It sounds like at least PyQtRibbon hasn't been installed.

It would probably be easier to use the Windows installer available [here](https://github.com/RoadrunnerWMC/Reggie-Next/releases/tag/v0.13-milestone-2-alpha-3)

**Comment by Shyguyfan101** [comment]
Does this answer your question?
![image](https://user-images.githubusercontent.com/73045476/99924937-f76fbb00-2cf0-11eb-8243-80347c1a3a68.png)

**Comment by Meorge** [comment]
Yes, if all you did was download the zip files, the modules haven't been installed. The process of installing them is a bit complex, so I'd advise to just use the installer exe [here](https://github.com/RoadrunnerWMC/Reggie-Next/releases/tag/v0.13-milestone-2-alpha-3).

**Comment by Shyguyfan101** [comment]
It worked! It's time to close this issue

**Comment by Meorge** [comment]
Glad it's working. Enjoy Reggie Next! :)
